### ISSUE TITLE
Message Nothing

### ISSUE THREAD

**Issue by ubergeekzone** [mevdschee/php-crud-ui#1]
I'd like to make use of this, any docs? I pointed it to my api and all i see is the message Nothing.

**Comment by mevdschee** [comment]
Hi, that message is emitted by the home page. You should click a link in the menu. The menu should list the tables in your database. You API must be php-crud-api based, is it?

**Comment by ubergeekzone** [comment]
yes it is, turns out my api was failing to the remote mysql host. connected
and it showed the menu list. thanks!

Thanks

Amy BridgesCEO & Full Stack Web Developer

(678) 872-3085 | invoate.com <http://www.invoate.com>
<http://www.invoate.com/>

[image: Twitter]  <http://www.twitter.com/invoate> [image: Facebook]
<http://www.facebook.com/invoate> [image: Google +]
<https://plus.google.com/+Invoate> [image: LinkedIn]
<https://www.linkedin.com/in/amy-bridges-ab33b336> [image: Skype]
<https://htmlsig.com/signatures/001C01XJ2/atlantawebco> [image: Github]
<http://www.github.com/ubergeekzone>

**Comment by mevdschee** [comment]
You are welcome. Thank you for your feedback.
