### ISSUE TITLE
New data entry not reflecting on database.

### ISSUE THREAD

**Issue by anushaath** [mevdschee/php-crud-ui#12]
Hi,

I've designed a cab-booking database and I'm using the PHP-CRUD-API and UI for this. I'm able to insert data into customer, driver , booking module. But I'm not able to insert data into the reservation module. I entered all the data, and it shows that it has been added, but when I check in the database, there is no entry.

**Comment by mevdschee** [comment]
I would love to, but there is no way I can help you based on the above description. You need to try to isolate the problem and be more specific.

**Comment by anushaath** [comment]
So first I add a new user, Rih Anna.

![capture1](https://cloud.githubusercontent.com/assets/11595241/22543598/43947bc4-e957-11e6-9568-c693d4d099af.PNG)
And the user is updated in the table:
![capture2](https://cloud.githubusercontent.com/assets/11595241/22543621/651803c4-e957-11e6-8160-7707a62bd761.PNG)

Now I make a booking for the user:

![capture3](https://cloud.githubusercontent.com/assets/11595241/22543639/828f3b3e-e957-11e6-8f20-a39ad2a7c813.PNG)

This is also reflected in the table:
![capture4](https://cloud.githubusercontent.com/assets/11595241/22543657/93a2ff3c-e957-11e6-962c-8bec118a40ad.PNG)

Now I assign a car to that user through reservation: 
![capture5](https://cloud.githubusercontent.com/assets/11595241/22543710/c9e95ff0-e957-11e6-872a-2408f3c8212f.PNG)


But this tuple is not there on the table!
![capture6](https://cloud.githubusercontent.com/assets/11595241/22543704/c30357b8-e957-11e6-9215-aa3801399114.PNG)

This is the problem I'm facing. I have no idea why.
When I add that tuple using phpMyAdmin, it is added in the table.

**Comment by anushaath** [comment]
I tried it with Postman, and it seems to be working fine.

![capture7](https://cloud.githubusercontent.com/assets/11595241/22544023/2df0016a-e959-11e6-9ffa-e92c367f314a.PNG)

**Comment by mevdschee** [comment]
Is the pk of the relationship table auto_increment?

**Comment by mevdschee** [comment]
If you rather send it private, then send it by email.

**Comment by anushaath** [comment]
I've attached the sql file here.

**Comment by anushaath** [comment]
Have you received the file?

**Comment by mevdschee** [comment]
Yes and I loaded your data and tried to reproduce your problem, but it seems it works here. The reservation is created and is listed.

**Comment by anushaath** [comment]
Can you provide a screen shot? I'll also try it on a different machine.

**Comment by mevdschee** [comment]
![selection_013](https://cloud.githubusercontent.com/assets/1288217/22582860/d2048010-e9e9-11e6-85f9-625dc8f8da8a.png)

**Comment by mevdschee** [comment]
Sorry.. it seems it does not work! Indeed.. give me a second to find it out.

**Comment by mevdschee** [comment]
The problem is that the database says:

    Error in query (1062): Duplicate entry '1' for key 'PRIMARY' 

This is due to the definition of reservation:

    DROP TABLE IF EXISTS `reservation`;
    CREATE TABLE `reservation` (
      `booking_id` int(7) NOT NULL,
      `car_reg_number` varchar(11) NOT NULL,
      `start_time` datetime NOT NULL,
      `end_time` datetime NOT NULL,
      `reserve_status` text NOT NULL,
      PRIMARY KEY (`booking_id`),
      KEY `car_reg_number` (`car_reg_number`),
      CONSTRAINT `reservation_ibfk_1` FOREIGN KEY (`booking_id`) REFERENCES `booking` (`booking_id`) ON DELETE NO ACTION ON UPDATE CASCADE,
      CONSTRAINT `reservation_ibfk_2` FOREIGN KEY (`car_reg_number`) REFERENCES `car` (`reg_number`) ON DELETE NO ACTION ON UPDATE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

As you see the primary key is `booking_id`, thus not allowing two records with the same booking_id.

**Comment by mevdschee** [comment]
I guess error handling needs to be improved :-)

**Comment by mevdschee** [comment]
| # | type | table | field | message |
| -- | --  | --  | --  | --   |
| 1. | warning | admin |  | collation should be utf8 |
| 2. | error | admin | id | must exist |
| 3. | warning | billing |  | collation should be utf8 |
| 4. | error | billing | booking_id | table 'bookings' should exist |
| 5. | error | billing | booking_id | must be foreign key |
| 6. | error | billing | id | must exist |
| 7. | warning | booking |  | collation should be utf8 |
| 8. | error | booking | booking_id | may not be primary key |
| 9. | error | booking | booking_id | may not auto increment |
| 10. | error | booking | booking_id | table 'bookings' should exist |
| 11. | error | booking | booking_id | must be foreign key |
| 12. | error | booking | customer_id | table 'customers' should exist |
| 13. | error | booking | customer_id | must be foreign key to 'customers.id' |
| 14. | error | booking | id | must exist |
| 15. | warning | car |  | collation should be utf8 |
| 16. | error | car | car_id | may not be primary key |
| 17. | error | car | car_id | may not auto increment |
| 18. | error | car | car_id | table 'cars' should exist |
| 19. | error | car | car_id | must be foreign key |
| 20. | error | car | id | must exist |
| 21. | warning | car_insurance |  | collation should be utf8 |
| 22. | error | car_insurance | id | must exist |
| 23. | warning | car_model |  | collation should be utf8 |
| 24. | error | car_model | id | must exist |
| 25. | warning | car_permit |  | collation should be utf8 |
| 26. | error | car_permit | id | must exist |
| 27. | warning | car_type |  | collation should be utf8 |
| 28. | error | car_type | id | must exist |
| 29. | warning | car_vendor |  | collation should be utf8 |
| 30. | error | car_vendor | vendor_id | may not be primary key |
| 31. | error | car_vendor | vendor_id | table 'vendors' should exist |
| 32. | error | car_vendor | vendor_id | must be foreign key to 'vendors.id' |
| 33. | error | car_vendor | id | must exist |
| 34. | warning | customer |  | collation should be utf8 |
| 35. | error | customer | customer_id | may not be primary key |
| 36. | error | customer | customer_id | may not auto increment |
| 37. | error | customer | customer_id | table 'customers' should exist |
| 38. | error | customer | customer_id | must be foreign key |
| 39. | warning | customer | DoB | invalid field name |
| 40. | warning | customer | email_id | should have index |
| 41. | error | customer | email_id | table 'emails' should exist |
| 42. | error | customer | email_id | must be foreign key |
| 43. | error | customer | id | must exist |
| 44. | warning | driver |  | collation should be utf8 |
| 45. | error | driver | driver_id | may not be primary key |
| 46. | error | driver | driver_id | may not auto increment |
| 47. | error | driver | driver_id | table 'drivers' should exist |
| 48. | error | driver | driver_id | must be foreign key |
| 49. | warning | driver | DoB | invalid field name |
| 50. | error | driver | id | must exist |
| 51. | warning | expense |  | collation should be utf8 |
| 52. | error | expense | id | must exist |
| 53. | warning | hours_worked |  | collation should be utf8 |
| 54. | error | hours_worked | driver_id | may not be primary key |
| 55. | error | hours_worked | driver_id | table 'drivers' should exist |
| 56. | error | hours_worked | driver_id | must be foreign key to 'drivers.id' |
| 57. | error | hours_worked | id | must exist |
| 58. | warning | reservation |  | collation should be utf8 |
| 59. | error | reservation | booking_id | may not be primary key |
| 60. | error | reservation | booking_id | table 'bookings' should exist |
| 61. | error | reservation | booking_id | must be foreign key to 'bookings.id' |
| 62. | error | reservation | id | must exist |
| 63. | warning | reserve_driver |  | collation should be utf8 |
| 64. | error | reserve_driver | driver_id | table 'drivers' should exist |
| 65. | error | reserve_driver | driver_id | must be foreign key |
| 66. | error | reserve_driver | booking_id | may not be primary key |
| 67. | error | reserve_driver | booking_id | table 'bookings' should exist |
| 68. | error | reserve_driver | booking_id | must be foreign key |
| 69. | error | reserve_driver | id | must exist |
| 70. | warning | tax_percent |  | collation should be utf8 |
| 71. | error | tax_percent | id | must exist |
| 72. | warning | vendor_details |  | collation should be utf8 |
| 73. | error | vendor_details | vendor_id | may not be primary key |
| 74. | error | vendor_details | vendor_id | may not auto increment |
| 75. | error | vendor_details | vendor_id | table 'vendors' should exist |
| 76. | error | vendor_details | vendor_id | must be foreign key |
| 77. | warning | vendor_details | email_id | should have index |
| 78. | error | vendor_details | email_id | table 'emails' should exist |
| 79. | error | vendor_details | email_id | must be foreign key |
| 80. | error | vendor_details | id | must exist |

**Comment by mevdschee** [comment]
That is what my "conventionist" script says about your data structure.

**Comment by anushaath** [comment]
So, I'll try to solve these first and then try the UI.php out later.

**Comment by mevdschee** [comment]
To avoid mistakes as the one you made with reservation, ensure that every table has a (technical) primary key named 'id'. It should auto increment as well. Whenever you make a foreign key to another table it should refer to that field in the table. If you want to avoid double entries, then use a unique constraint, possibly on multiple fields. Don't use extra tables for additional fields of an entity. Either make them nullable or give them a default value. Always define your FK relations. Those are my advices based on your data model. Currently when it is not inserting it is a constraint failing. This is most likely a "duplicate key" error from a primary key constraint.

**Comment by anushaath** [comment]
Issue solved! I added separate 'id' for every table. Changed all tables to utf8_unicode_ci and made all foriegn keys and the referenced keys' lengths the same. And voila!

Thanks for your quick guidance!

**Comment by mevdschee** [comment]
I'm glad you got it working, enjoy the software!
