### ISSUE TITLE
Picking out the data that are being updated to pass to another function

### ISSUE THREAD

**Issue by anushaath** [mevdschee/php-crud-ui#17]
I got it working in the createObject() for newly inserted data. Now, I've to call the function on every update of records as well. So, I think I've to use the updateObject() ?
One question is how do I get the key, table of the record in updateObject() ?
Is it $key[0], tables[0]?

**Comment by mevdschee** [comment]
Yes it is!

**Comment by anushaath** [comment]
Should I call the function after, '$this->db->query' OR '$this->db->affectedRows' ?

**Comment by anushaath** [comment]
Figured it out! Thanks!
