### ISSUE TITLE
Edit and Delete produce internal server error via UI.php but work with api.php

### ISSUE THREAD

**Issue by marchildmann** [mevdschee/php-crud-ui#18]
When I use the ui.php I am receiving the following errors for "EDIT" and "DELETE"

EDIT
Fatal error: Method name must be a string in api-sqlite/ui.php on line 252

DELETE
Fatal error: Method name must be a string in api-sqlite/ui.php on line 281

Everything works fine if I am using the api.php directly over an OSX tool called "CocoaRestClient"

**Comment by mevdschee** [comment]
Can you provide some more information? I have trouble reproducing this issue.
