### ISSUE TITLE
PUT/UPDATE not working on Webserver, but working on the localhost

### ISSUE THREAD

**Issue by anushaath** [mevdschee/php-crud-ui#19]
Hi
I tested 'ui.php' and 'api.php' on localhost (XAMPP). Its working fine. Now I uploaded it on an actual web server. I tested the API with postman for the web, and its working perfectly. But when I load the 'ui.php' file, the screen is blank. Nothing is displayed. I double checked if the problem was with Sessions, which I was using, but that is also working fine. I'm not able to locate the where the problem seems to be occurring. Any ideas?

**Comment by anushaath** [comment]
Is it ok if the server is running on PHP version 5.4 or 5.6?
 I see that the minimum requirement is v5.3

**Comment by anushaath** [comment]
I got it working after changing the version. 

Now the 'GET' request on the API is working well. But I tested the 'POST' request using postman and it says
> No Database

**Comment by anushaath** [comment]
I got it working. 

The edit and delete function are not working as expected.
They dont update anything in the db nor delete anything from the db

**Comment by anushaath** [comment]
I've changed the .htaccess  file also to allow PUT and DELETE request. But still not able to make it work.
Postman displays a 404 error.

**Comment by anushaath** [comment]
I think my error is similar to this [#93](https://github.com/mevdschee/php-crud-api/issues/93)
But, I dont know how to define that verb. Mine is hosted on GoDaddy.

**Comment by anushaath** [comment]
Dont really require the DELETE part in my project.

**Comment by mevdschee** [comment]
I plan to look into this tonight

**Comment by mevdschee** [comment]
I can't reproduce this issue. Can you provide more details?

**Comment by anushaath** [comment]
Yes. The link to the website is http://www.kickstartcabs.com/admin_login.php
username: git
pass: hubgit$67%

The API is at http://www.kickstartcabs.com/API.php
The PUT request is working via the postman for
http://www.kickstartcabs.com/API.php

But it doesn't work via the ui.php, which will come after the login.
In later versions, I'm planning to include password-less entry.

**Comment by anushaath** [comment]
I think it seems to be working as of now.
I think the problem was with the host as it was not allowing the PUT request for security reasons.
