### ISSUE TITLE
Listing referenced texts

### ISSUE THREAD

**Issue by anushaath** [mevdschee/php-crud-ui#22]
I want to show only certain values of certain columns if the field is referenced.

So after the if statement in line 92 I added another if statement like this: 

https://github.com/mevdschee/php-crud-ui/blob/master/ui.php#L92

if ($i=='first_name' || $i=='last_name' || $i=='model' || $i=='reg_number'||$i=='pickup_location' || $i=='start_time')

This should ideally print "Firstname- Lastname" for one table.
But it prints nothing. The field is blank.  I can't seem to figure it out. 
If I remove the above if statement, it prints everything.
Any ideas?

**Comment by mevdschee** [comment]
Variable $i represents the column number, not the column name.
