### ISSUE TITLE
Cannot figure out how to configure UI.php 

### ISSUE THREAD

**Issue by rmawani** [mevdschee/php-crud-ui#27]
Hi,

I've been trying to figure out what I'm doing wrong for the last hour or so but to no avail.

I have pointed ui.php to the working PHP-CRUD-API as follows:

`$ui = new PHP_CRUD_UI(array('url' => 'https://localhost/api/api.php',));`

Somehow, when I navigate to https://localhost/api/ui.php, I don't see a menu. All I get is the following Page Header, "PHP-CRUD-UI" and the message, "Nothing". 

I saw a previous Github Issue that was resolved with the same issue and I know it is definitely just a config problem on my end, but for the life of me, I just can't seem to figure out what I'm missing...

Any idea what I am doing wrong here?

Thanks so much in advance!

**Comment by mevdschee** [comment]
Is the api working? Do you see the swagger output when you go to https://localhost/api/api.php?

**Comment by rmawani** [comment]
Thanks for the quick reply!

Yes, the api is working and I can see the swagger output when I goto https://localhost/api/api.php.

**Comment by mevdschee** [comment]
Did you create any tables in the database?

**Comment by rmawani** [comment]
Yes, the database has about 15 tables, each of which have data.

**Comment by mevdschee** [comment]
Good. Do you see any error messages/warnings in the PHP log?

**Comment by rmawani** [comment]
I don't see any warnings/messages in the PHP Log...

**Comment by mevdschee** [comment]
Are you running both using a single "PHP -S"? That is not multi-threaded and does not support re-entry when the Curl call from ui.php calls api.php.

**Comment by rmawani** [comment]
Of that, I'm not certain as I'm using a hosted webserver. I should have probably mentioned that in my initial post. My feeling is that, since it is a hosted solution, multi-threading is supported.

Also, https://localhost/api/ui.php should have read https://mywebsite.com/api/ui.php...

**Comment by mevdschee** [comment]
>since it is a hosted solution, multi-threading is supported.

Agree

Can you add the following on line 32:

    die(var_dump($definition));

see: https://github.com/mevdschee/php-crud-ui/blob/master/ui.php#L32

And post the output here?

**Comment by rmawani** [comment]
It outputs NULL...

**Comment by mevdschee** [comment]
Ah.. can you remote that debug statement and add the following on line 20:

    die(var_dump($method, $url, $response));

https://github.com/mevdschee/php-crud-ui/blob/master/ui.php#L20

**Comment by rmawani** [comment]
Thanks for all your help! I finally got it working by just rebuilding the database and re-importing the data. One of the tables must have caused the issue.

Thanks again for the wonderful scripts!

**Comment by mevdschee** [comment]
I'm glad you got it working.
