### ISSUE TITLE
API queries not reflecting on UI

### ISSUE THREAD

**Issue by anushaath** [mevdschee/php-crud-ui#28]
Normal query to GET all data of a table works fine.
![capture1](https://cloud.githubusercontent.com/assets/11595241/26237946/b54d4d8c-3c94-11e7-8183-d4b07da1585b.PNG)

If I run a api query like 
![capture1](https://cloud.githubusercontent.com/assets/11595241/26238024/fab6b322-3c94-11e7-9673-d0f79e8ddf31.PNG)
on postman, it gives the correct result but on the UI.php it's all wrong.

This is the code:
![capture1](https://cloud.githubusercontent.com/assets/11595241/26238093/38151e0c-3c95-11e7-98f1-e5ce27ab5f59.PNG)

And this is the ui.
![capture1](https://cloud.githubusercontent.com/assets/11595241/26238218/c6db7456-3c95-11e7-874c-462a357be302.PNG)

The last entry, the booking_status is COMPLETED, and yet it is showing that row after running the neq query.
If I run the query, even the customer id, car id and driver id columns doesn't show any data.

The data is in the right format in postman, but not showing in ui.php

**Comment by mevdschee** [comment]
This is a request for search support (see: #39), but here it is assumed that the same parameter strategy is followed.

**Comment by mevdschee** [comment]
Search functionality is now implemented.
