### ISSUE TITLE
Warning: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by ubergeekzone** [mevdschee/php-crud-ui#3]
Warning: Invalid argument supplied for foreach() in ui.php on line 148

Warning: Invalid argument supplied for foreach() in ui.php on line 156

I see this error when trying to do a /list for any of my tables.. What could be the issue?

Thanks!

**Comment by mevdschee** [comment]
Please post those lines, as they do not seem to match the master's ui.php file, thank you.

**Comment by ubergeekzone** [comment]
Line 148:
```php
 foreach ($referenced as $i=>$relations) {
```

Line 156:
```php
                $html.= '</td>';
```

**Comment by ubergeekzone** [comment]
updated the comment to the correct lines, was looking at wrong file.

**Comment by ubergeekzone** [comment]
I have pinned down the issue, just not sure what the appropriate way to fix would be.. 


```php
print_r($url.'/'.$subject.'?'.http_build_query($args));
```
shows url as http://localhost:8888/folder/ui.php/tournaments/api/index.php/tournaments?

```php
$data = $this->call('GET',$url.'/'.$subject.'?'.http_build_query($args))
```

**Comment by ubergeekzone** [comment]
Did some more debugging and it was my base_url() function i created that was causing the issue, nothing with your code. i really need to quit the late night programming sessions.. lol

**Comment by mevdschee** [comment]
Ah.. that explains. Thank you for letting me know. Happy coding!
