### ISSUE TITLE
Lazy loading for large record sets?

### ISSUE THREAD

**Issue by ablears** [mevdschee/php-crud-ui#30]
Hi @mevdschee, great work with the CRUD library. 

Do you have any suggestions for usability when returning large record sets (eg lazy loading rows so the browser doesn't time out/crash)?

**Comment by naskobulgaria** [comment]
Can i ask you how many rows do you return? I ask because i want to use that php=crud=ui with 20000 rows and i wonder how it will work.

**Comment by ablears** [comment]
300,000+ rows. I am investigating using W2UI (javascript framework) for the display and lazy loading. See http://w2ui.com/web/demos/#!grid/grid-3 for a demo. The PHP CRUD API returns JSON, it just needs tweaking to return the schema expected by W2UI.

**Comment by mevdschee** [comment]
@ablears contrary to php-crud-api, the php-crud-ui project does not support streaming, so I would recommend to avoid using it for large record sets. I am not aware of any other implementations that handle this gracefully.

**Comment by ablears** [comment]
Thanks @mevdschee. I have php-crud-api working with http://w2ui.com now, so I'll use that instead (it handles lazy loading).

**Comment by mevdschee** [comment]
w2ui is pretty awesome. I love this example: http://w2ui.com/web/demos/#!combo/combo-4

**Comment by naskobulgaria** [comment]
@ablears ablears can you give some jockers how did you implemented php-crud-api qith w2ui?

**Comment by ablears** [comment]
@naskobulgaria See my quick gist here: https://gist.github.com/ablears/23ea8fe6a14c4e63315583805779e9b8 

The format_for_w2grid() function takes the php-crud-api output and formats the JSON for w2ui.
