### ISSUE TITLE
not showing recent

### ISSUE THREAD

**Issue by baroninn** [mevdschee/php-crud-ui#31]
So, I just wanted to give you guys a heads up.
Maybe this is not the correct way to solve the issue, but it helped me out.

The UI was now showing recent tables when I created them in the database.
So after hours of cache-control tests, I finally figured out to place session_destroy(); at the end of the ui.php file :-)

Can you guys confirm that this is safe and correct way to solve my issue ?
and also if this will not create problems in other areas ?

thanks
oh and thanks for creating this and make it open for public. Im having a blast with it :-)

**Comment by mevdschee** [comment]
Hi @baroninn, glad you like the project. The code is optimizing by storing the definition in the session variable. You may just clear your (session) cookie to show the latest. It is safer than adding "session_destroy()". Enjoy!

**Comment by baroninn** [comment]
Hi Mevdschee
Thank you for a quick reply

Im no expert so I ask if this is correct way to clear session : 
place this at the end of file : 
$_SESSION = array();

?

**Comment by mevdschee** [comment]
Clearing the cookie is something the user does in the browser. Removing the session on the server is done with "session_destroy()" as you already did.

**Comment by baroninn** [comment]
Ah, thanks for the clarity.
I know you are busy, so i'll keep this the last question :-)
Thanks for the time btw.

You say that it is safer to clear the cookie on the client side.

If I wanted to clear this on the server side, would the best/safest method be :

<?php
  $lifetime=600;
  session_set_cookie_params($lifetime);
  session_start();
?>

or maybe session_destroy is alright.
i dont want to loose any data.

**Comment by mevdschee** [comment]
>If I wanted to clear this on the server side

"session_destroy" is the way to do that.
