### ISSUE TITLE
View on error

### ISSUE THREAD

**Issue by thipages** [mevdschee/php-crud-ui#35]
Hi,
I have an error when try to "view
Other CRUD functions work

![image](https://user-images.githubusercontent.com/130309/55754916-0509fb80-5a4e-11e9-8ad1-95f4c97c48d6.png)

Note : the usage of compact/extract is (for me) difficult to read the code, and not IDE friendly.

**Comment by mevdschee** [comment]
Thank you for reporting this issue. 

>Note : the usage of compact/extract is (for me) difficult to read the code, and not IDE friendly.

I agree, and it should be avoided. The code should be rewritten in the same way I did with v2 for PHP-CRUD-API with PSR compliance, a build step and multiple files.

Did the fix help?

**Comment by mevdschee** [comment]
>Note : the usage of compact/extract is (for me) difficult to read the code, and not IDE friendly.

I agree, and it should be avoided. The code should be rewritten in the same way I did with v2 for PHP-CRUD-API with PSR compliance, a build step and multiple files.

I've split this into a separate issue.

**Comment by thipages** [comment]
fixed
