### ISSUE TITLE
the usage of compact/extract

### ISSUE THREAD

**Issue by mevdschee** [mevdschee/php-crud-ui#36]
From (#35):

>Note : the usage of compact/extract is (for me) difficult to read the code, and not IDE friendly.

I agree, and it should be avoided. The code should be rewritten in the same way I did with v2 for PHP-CRUD-API with PSR compliance, a build step and multiple files.

**Comment by thipages** [comment]
An intermediate step could  be to add a value object representing the config

**Comment by thipages** [comment]
If you could manage the intermediate step, it may facilitate a complementary  javascript implementation I would like to start

**Comment by mevdschee** [comment]
>a complementary javascript implementation

Are you sure? Did you look at: https://github.com/nlware/vue-crud-ui?

**Comment by thipages** [comment]
yes I have looked at it. However II would like to build something different
1. A specific minimalist javascript API for cruding a database with php-crud-api on server side (on the way)
2. A view (gui) based on [lighterhtml ](https://github.com/WebReflection/lighterhtml)(a bit different than vuejs)

**Comment by mevdschee** [comment]
>I would like to build something different

Sounds like a fun project. Enjoy!

**Comment by mevdschee** [comment]
I hope this helps :-)

**Comment by thipages** [comment]
Hi,
yes it is fine,
Thank you

Note : there is one unknown variable, the last I think ($record[ line 275](https://github.com/mevdschee/php-crud-ui/blob/master/ui.php#L275))

**Comment by mevdschee** [comment]
Thank you fixed it!
