### ISSUE TITLE
Getting error when browsing to http://localhost:8081/ui.php

### ISSUE THREAD

**Issue by pawiromitchel** [mevdschee/php-crud-ui#43]
![image](https://user-images.githubusercontent.com/11035568/61827026-09f68d80-ae3a-11e9-9873-f4b1b53c0a69.png)

**Comment by mevdschee** [comment]
Thank you for reaching out. I think you need to install the 'php-curl' package.

**Comment by pawiromitchel** [comment]
Ahh, got it working, thanks! Closing issue.
