### ISSUE TITLE
Warning: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by nenas04** [mevdschee/php-crud-ui#5]
I want to use your ui for my api (based on php-crud-api), but I get that error: "Warning: Invalid argument supplied for foreach()". The error is in the function "menu", code here:

```
function menu($parameters) {
        extract($parameters);
        $html= '<ul class="nav nav-pills nav-stacked">';
        foreach ($definition['tags'] as $tag) {
            $active = $tag['name']==$subject?' class="active"':'';
            $html.= '<li'.$active.'><a href="'.$this->url($base,$tag['name'],'list').'">'.$tag['name'].'</a></li>';
        }
        $html.= '</ul>';
        return $html;
    }
```

What is wrong? Help me please! Thank you.

**Comment by mevdschee** [comment]
Maybe it cannot find the api.php url?

**Comment by nenas04** [comment]
But I'm giving the correct path here:

```
$ui = new PHP_CRUD_UI(array(
    'url' => '/api_v1/api.php',
    'pagination_limit' => 5
));

echo $ui->executeCommand();
```

I'm not seeing what is wrong...

**Comment by pottertech** [comment]
I have modified the menu function to better deal with the $definition variable being sometimes being empty:

function menu($parameters) {
    extract($parameters);

    $html= '<ul class="nav nav-pills nav-stacked">';
    if (is_array($definition)) {
    foreach ($definition['tags'] as $tag) {
        $active = $tag['name']==$subject?' class="active"':'';
        $html.= '<li'.$active.'><a href="'.$this->url($base,$tag['name'],'list').'">'.$tag['name'].'</a></li>';
    }
}
    $html.= '</ul>';
    return $html;
}

**Comment by mevdschee** [comment]
Does this fix help?

**Comment by mevdschee** [comment]
Closed due to inactivity.
