### ISSUE TITLE
Load config.php without modifying ui.php?

### ISSUE THREAD

**Issue by zemian** [mevdschee/php-crud-ui#51]
It would nice to able to load a config.php with parameters without have to modify ui.php itself. 

In your PHP-CRUD-API project, you have included a "api.include.php" that user may create their own api.php, but not so with ui.php? Because of this, user must modify ui.php to setup any config changes. Hence I propose to either support same include file, or better yet auto detect a config.php file that let user set parameters.

**Comment by mevdschee** [comment]
Supported in v2.13
