### ISSUE TITLE
can't edit records

### ISSUE THREAD

**Issue by dirkk0** [mevdschee/php-crud-ui#58]
Hi,

  I must be understanding something very wrong: I see the list of tables and items, but I am not able to edit them:
  
![image](https://github.com/mevdschee/php-crud-ui/assets/625394/f302215f-6ae2-4afe-9c7a-2a052de25c98)

Can you advise?
Thanks Dirk
PS: this is sqlite which might be the problem.

**Comment by dirkk0** [comment]
And one more:
![image](https://github.com/mevdschee/php-crud-ui/assets/625394/ff82299c-c119-42ac-b935-24c3e0d6d09f)
While editing existing records now works, adding a 'new item' does not.
Might this be related to the mandatory 'id'?

**Comment by dirkk0** [comment]
Yes, it is - the id needs to be autoincremented.

According to the sqlite documentation, autoincrement should be avoided.

**Comment by mevdschee** [comment]
>According to the sqlite documentation, autoincrement should be avoided.

Yeah.. they prefer the use of the "ROWID". Note that there no real problem when you do create an auto-incrementing primary key called "ID", even though the manual says it is a waste of compute and storage.

see: https://www.sqlite.org/autoinc.html

**Comment by dirkk0** [comment]
oh interesting!
yes, this is what I did and it worked fine.

This is what I used in my tests and it works great with php-crud-ui and -api:
```
DROP TABLE IF EXISTS cal;
CREATE TABLE cal (
   ID INTEGER PRIMARY KEY AUTOINCREMENT,
   user          TEXT    NOT NULL,
   type          TEXT    NOT NULL,
   name          TEXT    NOT NULL,
   start         TEXT    NOT NULL,
   end           TEXT    NOT NULL,
   details       TEXT    NOT NULL
);
INSERT INTO cal (user,type,name,start,end,details) VALUES ('u1','band','p1', '2023-06-01 15:00', '2023-06-01 17:00', '');
INSERT INTO cal (user,type,name,start,end,details) VALUES ('u1','band','p2', '2023-06-01 18:00', '2023-06-01 20:00', '');
```
The same statements work with mysql if `AUTOINCREMENT` is changed to `AUTO_INCREMENT`.

**Comment by mevdschee** [comment]
Great, thank you for reporting your success.
